version: "3"

services:
  ubuntu-yarn:
    container_name: mybuntu
    user: root
    build:
      context: .
    volumes:
      - .:/app
      -  /d/Repos/.ssh:/root/.ssh
    ports:
      - "8080:8080"
      - "8081:8081"
    command: >
      sh -c "/bin/bash"
    stdin_open: true # docker run -i
    tty: true        # docker run -t